apps/blog/urls.py
from django.conf.urls import url,include
from . import views
from .feeds import ArticleFeed
app_name = "blog"
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^single/(\d+)/$',views.SingleView.as_view(),name="single"),
    url(r'^addarticle/$',views.AddArticleView.as_view(),name="addarticle"),
    url(r'^archives/(\d+)/(\d+)/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^categorys/(\d+)/$',views.CategorysView.as_view(),name='categorys'),
    url(r'^tags/(\d+)/$',views.TagsView.as_view(),name='tags'),
    url(r'^rss/$',ArticleFeed(),name='rss'),
]

demo3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
import xadmin
from .settings import MEDIA_ROOT
# server用于处理用户上传
from django.views.static import serve
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/',xadmin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    url('ueditor/',include("DjangoUeditor.urls")),
    url('search/',include('haystack.urls')),
    path('',include('blog.urls', namespace='blog')),
    path('',include('comment.urls', namespace='comment')),

]

extract_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/comment/models.py
from django.db import models
from blog.models import Article
# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=20)
    url = models.URLField(blank=True,null=True,default="http://www.baidu.com")
    email = models.EmailField(blank=True,null=True)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article,on_delete=models.CASCADE)

templates/search/search.html
<!DOCTYPE html>
<html>
<head>
    <title>搜索结果页面</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>
</head>

<body>

<div id="site-header">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>博客实战</b></a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="index.html" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                {% for article in page.object_list %}
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blog:single' article.object.id %}">{{article.object.title}}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{article.object.category}}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{article.object.create_time}}</time></a></span>
                            <span class="post-author"><a href="#">{{article.object.author}}</a></span>
                            <span class="comments-link"><a href="#">{{article.object.comment_set.count}} 评论</a></span>
                            <span class="views-count"><a href="#">{{article.object.views}} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{article.object.body|safe}}
                        <div class="read-more cl-effect-14">
                            <a href="#" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% endfor %}


                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->

                {% comment %}
                <div class="pagination">
                    <ul>
                        <li><a href="">1</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">4</a></li>
                        <li><a href="">5</a></li>
                        <li class="current"><a href="">6</a></li>
                        <li><a href="">7</a></li>
                        <li><a href="">8</a></li>
                        <li><a href="">...</a></li>
                        <li><a href="">11</a></li>
                    </ul>
                </div>
                {% endcomment %}
            </main>

        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>