apps/blog/urls.py
from django.conf.urls import url,include
from . import views
from .feeds import ArticleFeed
app_name = "blog"
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^single/(\d+)/$',views.SingleView.as_view(),name="single"),
    url(r'^addarticle/$',views.AddArticleView.as_view(),name="addarticle"),
    url(r'^archives/(\d+)/(\d+)/$',views.ArchivesView.as_view(),name='archives'),
    url(r'^categorys/(\d+)/$',views.CategorysView.as_view(),name='categorys'),
    url(r'^tags/(\d+)/$',views.TagsView.as_view(),name='tags'),
    url(r'^rss/$',ArticleFeed(),name='rss'),
]

apps/comment/urls.py
from django.conf.urls import url
app_name = "comment"
from . import views
urlpatterns = [
    url(r'^comment/(\d+)/$',views.AddComment.as_view(),name="comment"),
]

demo3/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
import xadmin
from .settings import MEDIA_ROOT
# server用于处理用户上传
from django.views.static import serve
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('xadmin/',xadmin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    url('ueditor/',include("DjangoUeditor.urls")),
    url('search/',include('haystack.urls')),
    path('',include('blog.urls', namespace='blog')),
    path('',include('comment.urls', namespace='comment')),

]

extract_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from DjangoUeditor.models import UEditorField
# Create your models here.
class Ads(models.Model):
    img = models.ImageField(upload_to="ads")
    desc = models.CharField(max_length=20)
    index = models.IntegerField(default=0)

    def __str__(self):
        return self.desc

class Category(models.Model):
    title = models.CharField(max_length=20)
    def __str__(self):
        return self.title

class Tag(models.Model):
    title = models.CharField(max_length=10)
    def __str__(self):
        return self.title

class Article(models.Model):
    title = models.CharField(max_length=20)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    views = models.IntegerField(default=0)
    # body = models.TextField()
    body = UEditorField(imagePath="articleimg/",width="100%")
    tags = models.ManyToManyField(Tag)
    def __str__(self):
        return self.title

apps/comment/models.py
from django.db import models
from blog.models import Article
# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=20)
    url = models.URLField(blank=True,null=True,default="http://www.baidu.com")
    email = models.EmailField(blank=True,null=True)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article,on_delete=models.CASCADE)

apps/blog/forms.py
from django import forms
from .models import Article
from comment.models import Comment
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","body"]
        widgets = {
            "title":forms.TextInput(attrs={"class":"form-control"})
        }
        labels = {
            "title":"文章标题",
            "body":"文章正文"
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name","email","url","content"]

apps/blog/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.views.generic import View
from django.http import HttpResponse
from .models import *
from .forms import ArticleForm,CommentForm
# Create your views here.
from django.core.paginator import Paginator,Page
from django.views.decorators.cache import cache_page
from django.core.cache import cache

def getpage(request,object_list,per_num):
    pagenum = request.GET.get("page")
    pagenum = 1 if not pagenum else pagenum
    page = Paginator(object_list, per_num).get_page(pagenum)
    return page

# @cache_page(timeout=60)
def index(request):
    value = cache.get("py1905")
    print(value)
    cache.set("py1905","hi")
    value = cache.get("py1905")
    print(value)
    cache.clear("py1905")
    value = cache.clear("py1905")
    print(value)

    articles = Article.objects.all()
    page = getpage(request, articles, 1)
    return render(request, 'blog/index.html', {"page": page})


class IndexView(View):

    def get(self,request):
        articles = Article.objects.all()
        # paginator = Paginator(articles,1)
        # print(paginator.page_range) #[1,5]
        # print(paginator.object_list) #
        # print(paginator.num_pages) #4
        # print(paginator.count) #4
        # page = paginator.get_page(3)
        # print(page)
        # print(page.paginator is paginator )
        # print(page.object_list)
        # print(page.number)
        # print(page.next_page_number())
        # print(page.previous_page_number())
        # print(page.has_next())
        # print(page.has_previous())

        page = getpage(request,articles,1)

        return render(request,'blog/index.html',{"page":page})

class SingleView(View):

    def get(self,request,id):
        article = get_object_or_404(Article, pk=id)
        article.views += 1
        article.save()
        cf = CommentForm()
        return render(request,'blog/single.html',{"article":article,"cf":cf})
    def post(self,request,id):
        article = get_object_or_404(Article, pk=id)
        cf = CommentForm(request.POST)
        comment = cf.save(commit=False)
        comment.article = article
        comment.save()
        return redirect(reverse("blog:single", args=(article.id,)))

class AddArticleView(View):
    def get(self,request):
        af = ArticleForm()
        return render(request,'blog/addarticle.html',locals())
    def post(self,request):
        af = ArticleForm(request.POST)
        if af.is_valid():
            article = af.save(commit=False)
            article.category = Category.objects.first()
            article.author = User.objects.first()
            article.save()
            return redirect(reverse('blog:index'))
        return HttpResponse("添加失败")

class ArchivesView(View):
    def get(self,request,year,month):
        articles = Article.objects.filter(create_time__year=year, create_time__month=month)
        page = getpage(request, articles, 1)
        return render(request,"blog/index.html",{"page":page})

class CategorysView(View):
    def get(self,request,id):
        category = get_object_or_404(Category,pk=id)
        articles = category.article_set.all()
        page = getpage(request,articles,1)
        return render(request,'blog/index.html',{"page":page})

class TagsView(View):
    def get(self,request,id):
        tag = get_object_or_404(Tag,pk=id)
        articles = tag.article_set.all()
        page = getpage(request,articles,1)
        return render(request, 'blog/index.html', {"page": page})

extract_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/blog/addarticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title></title>
    {% endblock %}

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>


</head>

<body>

<div id="site-header">
	<div class="container">
		<div class="row">
				<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
								<h1><a href="{% url 'blog:index' %}"><b>博客实战</b></a></h1>
						</div>
				</div><!-- col-md-4 -->
				<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
								<div class="navbar-header">
										<button type="button" id="trigger-overlay" class="navbar-toggle">
												<span class="ion-navicon"></span>
										</button>
								</div>

								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav navbar-right">
												<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
												<li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
												<li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
										</ul>
								</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
								<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
								<div id="search-form" class="search-form">
										<form role="search" method="get" id="searchform" action="#">
												<input type="search" placeholder="搜索" required>
												<button type="submit"><span class="ion-ios-search-strong"></span></button>
										</form>
								</div>
						</div>
				</div><!-- col-md-8 -->
		</div>
	</div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {{ af.media }}
                <form action="" method="post">
                    {% csrf_token %}
                    {{ af }}
                    <br>
                    <div class="col-md-4 col-md-offset-4">
                        <input type="submit" value="添加" class="form-control">
                    </div>

                </form>


            </main>
        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

templates/blog/base.html
<!DOCTYPE html>
{% load my_func %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title></title>
    {% endblock %}

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/css/pace.css">
    <link rel="stylesheet" href="/static/css/custom.css">

    <!-- js -->
    <script src="/static/js/jquery-2.1.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/pace.min.js"></script>
    <script src="/static/js/modernizr.custom.js"></script>


</head>

<body>

<div id="site-header">
	<div class="container">
		<div class="row">
				<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
								<h1><a href="{% url 'blog:index' %}"><b>博客实战</b></a></h1>
						</div>
				</div><!-- col-md-4 -->
				<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
								<div class="navbar-header">
										<button type="button" id="trigger-overlay" class="navbar-toggle">
												<span class="ion-navicon"></span>
										</button>
								</div>

								<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
										<ul class="nav navbar-nav navbar-right">
												<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
												<li class="cl-effect-11"><a href="#" data-hover="博客">博客</a></li>
												<li class="cl-effect-11"><a href="#" data-hover="联系">联系</a></li>
										</ul>
								</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
								<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
								<div id="search-form" class="search-form">
										<form role="search" method="get" id="searchform" action="/search/">
												<input type="search" placeholder="搜索" required name="q">
												<button type="submit"><span class="ion-ios-search-strong"></span></button>
										</form>
								</div>
						</div>
				</div><!-- col-md-8 -->
		</div>
	</div>
</div>
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block left %}

                {% endblock %}
            </main>
            <aside class="col-md-4">
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% getlatestarticles 5 as latestarticles %}
                        {% for a in latestarticles %}
                        <li>
                            <a href="{% url 'blog:single' a.id %}">{{ a.title }}</a>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% gettimes as times %}
                        {% for o in times %}
                            <li>
                                <a href="{% url 'blog:archives' o.year o.month %}">{{o.year}} 年 {{o.month}} 月</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% getcategorys as categorys %}
                        {% for o in categorys %}
                             <li>
                                <a href="{% url 'blog:categorys' o.id %}">{{o.title}}<span class="post-count">({{o.article_set.count}})</span></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% gettags as tags %}
                        {% for o in tags %}
                            <li>
                            <a href="{% url 'blog:tags' o.id %}">{{ o.title }}</a>
                        </li>
                        {% endfor %}

                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<div id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2019 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="zzy0371">zzy0371</a>
                    - 由<a href="https://github.com/" title="github" target="_blank">zzy0371</a>修改
                </p>
            </div>
        </div>
    </div>
</div>

<script src="/static/js/script.js"></script>

</body>
</html>

templates/blog/single.html
{% extends 'blog/base.html' %}
{% block title %}
<title> 文章详情 </title>
{% endblock %}


{% block left %}
<article class="post post-{{article.id}}">
    <header class="entry-header">
        <h1 class="entry-title">{{article.title}}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{article.category.title}}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="2012-11-09T23:15:57+00:00">{{article.create_time}}</time></a></span>
            <span class="post-author"><a href="#">{{article.author.username}}</a></span>
            <span class="comments-link"><a href="#">{{article.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="#">{{article.views}} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{article.body|safe}}
    </div>
</article>


<section class="comment-area" id="comment-area">

    {% comment %}
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'blog:single' article.id  %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="id_name">名字：</label>
                {{ cf.name }}
            </div>
            <div class="col-md-4">
                <label for="id_email">邮箱：</label>
                {{ cf.email }}
            </div>
            <div class="col-md-4">
                <label for="id_url">网址：</label>
                {{ cf.url }}
            </div>
            <div class="col-md-12">
                <label for="id_content">评论：</label>
                {{ cf.content }}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>    <!-- row -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ article.comment_set.count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">

            {% for o in article.comment_set.all %}
            <li class="comment-item">
                <span class="nickname">{{ o.name }}</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ o.create_time }}</time>
                <div class="text">
                    {{ o.content }}
                </div>
            </li>
            {% endfor %}


        </ul>
    </div>
    {% endcomment %}










    <br><br><br><br><br>
    <h1>使用AJAX添加评论</h1>

    <div class="comment-form">
        <div class="row">
            <div class="col-md-4">
                <label for="id_name">名字：</label>
                {{ cf.name }}
            </div>
            <div class="col-md-4">
                <label for="id_email">邮箱：</label>
                {{ cf.email }}
            </div>
            <div class="col-md-4">
                <label for="id_url">网址：</label>
                {{ cf.url }}
            </div>
            <div class="col-md-12">
                <label for="id_content">评论：</label>
                {{ cf.content }}
                <button class="comment-btn" id="btn_commit">发表</button>
            </div>
        </div>    <!-- row -->
    </div>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ article.comment_set.count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled" id="commentlist2">

            {% for o in article.comment_set.all %}
            <li class="comment-item">
                <span class="nickname">{{ o.name }}</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ o.create_time }}</time>
                <div class="text">
                    {{ o.content }}
                </div>
            </li>
            {% endfor %}


        </ul>
    </div>
</section>


<script>
    $(function(){
        $("#btn_commit").click(function(){
            $.ajax({
                url:"{% url 'comment:comment' article.id %}",
                type:"post",
                data:{
                "name": $("#id_name").val(),
                "email":$("#id_email").val(),
                "url":$("#id_url").val(),
                "content":$("#id_content").val(),
                "csrfmiddlewaretoken":"{{ csrf_token }}",
                },
                success:function(data){
                            $("#id_name").val(""),
                            $("#id_email").val(""),
                            $("#id_url").val(""),
                            $("#id_content").val(""),
                     $("#commentlist2").append('<li class="comment-item"><span class="nickname">'+ data.name+ '</span></li><time class="submit-date" datetime="2012-11-09T23:15:57+00:00">'+data.create_time+'</time><div class="text">'+ data.content+'</div>');
                }
            });
        })
    })
</script>

{% endblock %}